<a href="https://colab.research.google.com/github/Jamakasilwane/EDSA_Zindi_Hackathon/blob/master/Optimizing_model_with_the_Ridge_Lasso_Train_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing libraries
import pandas as pd
import numpy as np

# Training Dataset


In [0]:
# loading the dataset as a pandas dataframe
train = pd.read_csv('Train.csv')

In [690]:
# Number of rows and colummns in a dataframe
train.shape

(21201, 29)

In [691]:
# First five rows of the dataframe
train.head()

Order No       User Id  ...      Rider Id  Time from Pickup to Arrival
0   Order_No_4211   User_Id_633  ...  Rider_Id_432                          745
1  Order_No_25375  User_Id_2285  ...  Rider_Id_856                         1993
2   Order_No_1899   User_Id_265  ...  Rider_Id_155                          455
3   Order_No_9336  User_Id_1402  ...  Rider_Id_855                         1341
4  Order_No_27883  User_Id_1737  ...  Rider_Id_770                         1214

[5 rows x 29 columns]

In [0]:
# Independent variables or features
X = train.drop(['Order No','User Id','Vehicle Type','Placement - Time',
                'Confirmation - Time','Arrival at Pickup - Time', 
                'Pickup - Time','Arrival at Destination - Day of Month',
                'Arrival at Destination - Weekday (Mo = 1)', 'Arrival at Destination - Time', 
                'Temperature', 'Precipitation in millimeters','Rider Id', 
                'Time from Pickup to Arrival','Platform Type',
                'Confirmation - Weekday (Mo = 1)','Arrival at Pickup - Weekday (Mo = 1)',
                'Pickup - Day of Month','Pickup - Weekday (Mo = 1)',
                'Placement - Day of Month','Pickup Long','Destination Lat',
                'Destination Long','Confirmation - Day of Month'],
                 axis=1)

In [0]:
# dependent\ response variable 
y = train.iloc[:,-1]

In [694]:
# First five rows of features
X.head()

Personal or Business  Placement - Weekday (Mo = 1)  ...  Distance (KM)  Pickup Lat
0             Business                             5  ...              4   -1.317755
1             Personal                             5  ...             16   -1.351453
2             Business                             2  ...              3   -1.308284
3             Business                             5  ...              9   -1.281301
4             Personal                             1  ...              9   -1.266597

[5 rows x 5 columns]

In [695]:
# First five rows of dependent variable
y.head()

0     745
1    1993
2     455
3    1341
4    1214
Name: Time from Pickup to Arrival, dtype: int64

In [696]:
# Number of rows and columns of independent variables
X.shape

(21201, 5)

In [697]:
# number of rows for dependent variable
y.shape

(21201,)

In [0]:
# Importing a class module to convert and transform categorical varable to numbers
# and transform the independent variables into a numpy array
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X_trans = ct.fit_transform(X)

In [699]:
# Converted features into a numpy array
X_trans

array([[ 1.       ,  0.       ,  5.       ,  9.       ,  4.       ,
        -1.3177547],
       [ 0.       ,  1.       ,  5.       , 12.       , 16.       ,
        -1.351453 ],
       [ 1.       ,  0.       ,  2.       , 30.       ,  3.       ,
        -1.3082842],
       ...,
       [ 1.       ,  0.       ,  4.       ,  7.       , 20.       ,
        -1.2860183],
       [ 0.       ,  1.       ,  3.       ,  4.       , 13.       ,
        -1.2500304],
       [ 1.       ,  0.       ,  2.       , 26.       , 12.       ,
        -1.2551895]])

In [700]:
# Number of rows and columns for independent varuables
X_trans.shape

(21201, 6)

In [0]:
# Deleting the second column of the converted categorical variable since it had only two categories
X_trans = np.delete(X_trans,1,axis=1)

In [702]:
# Independent variables without the second column of the categorical variable
X_trans

array([[ 1.       ,  5.       ,  9.       ,  4.       , -1.3177547],
       [ 0.       ,  5.       , 12.       , 16.       , -1.351453 ],
       [ 1.       ,  2.       , 30.       ,  3.       , -1.3082842],
       ...,
       [ 1.       ,  4.       ,  7.       , 20.       , -1.2860183],
       [ 0.       ,  3.       ,  4.       , 13.       , -1.2500304],
       [ 1.       ,  2.       , 26.       , 12.       , -1.2551895]])

In [703]:
# Number of rows and columns after removing one dumy variable
X_trans.shape

(21201, 5)

In [704]:
# Training the model with X and y values
# Importing the class to train our model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_trans,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [705]:
# Intercept
b_0 = lr.intercept_
b_0

1420.5343635313725

In [706]:
# Coefficients of each independent variable
coeff = pd.DataFrame(lr.coef_, X.columns, columns=['Coefficients'])
coeff

Coefficients
Personal or Business                -45.061256
Placement - Weekday (Mo = 1)          4.480188
Arrival at Pickup - Day of Month     -1.141963
Distance (KM)                       101.530761
Pickup Lat                          615.317335

# Test Dataset

In [0]:
# Import the dataset as a dataframe
test = pd.read_csv('Test.csv')

In [708]:
# Number of rows and columns in test dataset
test.shape

(7068, 25)

In [709]:
# First five rows of the test dataset
test.head()

Order No       User Id  ... Destination Long      Rider Id
0  Order_No_19248  User_Id_3355  ...        36.822390  Rider_Id_192
1  Order_No_12736  User_Id_3647  ...        36.823907  Rider_Id_868
2    Order_No_768  User_Id_2154  ...        36.851365   Rider_Id_26
3  Order_No_15332  User_Id_2910  ...        36.790658  Rider_Id_685
4  Order_No_21373  User_Id_1205  ...        36.792161  Rider_Id_858

[5 rows x 25 columns]

In [0]:
# Matching the independent variables of the test dataset to the train dataset 
X_test = test.drop(['Order No','User Id',
                    'Vehicle Type','Placement - Time',
                    'Confirmation - Time','Arrival at Pickup - Time',
                    'Pickup - Time', 'Temperature', 
                    'Precipitation in millimeters','Rider Id',
                    'Platform Type','Confirmation - Weekday (Mo = 1)',
                    'Arrival at Pickup - Weekday (Mo = 1)','Pickup - Day of Month',
                    'Pickup - Weekday (Mo = 1)', 'Pickup - Weekday (Mo = 1)',
                      'Placement - Day of Month','Pickup Long','Destination Lat',
                    'Destination Long','Confirmation - Day of Month'], axis=1)

In [711]:
# Number of rows and columns 
X_test.shape

(7068, 5)

In [712]:
# First five rows
X_test.head()

Personal or Business  Placement - Weekday (Mo = 1)  ...  Distance (KM)  Pickup Lat
0             Business                             3  ...              8   -1.333275
1             Business                             5  ...              5   -1.272639
2             Business                             4  ...              5   -1.290894
3             Business                             1  ...              5   -1.290503
4             Business                             2  ...              6   -1.281081

[5 rows x 5 columns]

In [0]:
# convert and transform categorical varable to numbers
# transform the independent variables into a numpy array
X_test_trans = ct.fit_transform(X_test)

In [714]:
X_test_trans

array([[ 1.       ,  0.       ,  3.       , 27.       ,  8.       ,
        -1.3332749],
       [ 1.       ,  0.       ,  5.       , 17.       ,  5.       ,
        -1.272639 ],
       [ 1.       ,  0.       ,  4.       , 27.       ,  5.       ,
        -1.290894 ],
       ...,
       [ 1.       ,  0.       ,  3.       ,  5.       , 10.       ,
        -1.3014461],
       [ 0.       ,  1.       ,  2.       , 29.       , 18.       ,
        -1.2484042],
       [ 1.       ,  0.       ,  2.       ,  4.       ,  8.       ,
        -1.2551895]])

In [0]:
# Removing one dummy variable
X_test_trans = np.delete(X_test_trans,1,axis=1)

In [716]:
X_test_trans

array([[ 1.       ,  3.       , 27.       ,  8.       , -1.3332749],
       [ 1.       ,  5.       , 17.       ,  5.       , -1.272639 ],
       [ 1.       ,  4.       , 27.       ,  5.       , -1.290894 ],
       ...,
       [ 1.       ,  3.       ,  5.       , 10.       , -1.3014461],
       [ 0.       ,  2.       , 29.       , 18.       , -1.2484042],
       [ 1.       ,  2.       ,  4.       ,  8.       , -1.2551895]])

# Predicting the times


In [717]:
# Time predictions of each order in a dataframe
y_test_trans_pred = list(lr.predict(X_test_trans))
y_test_pred_list = [int(round(i)) for i in y_test_trans_pred]
y_test_pred_df = pd.DataFrame(y_test_pred_list, columns=['Time from Pickup to Arrival'])
final_df = pd.concat([test.iloc[:,][['Order No']], y_test_pred_df], axis=1)
final_df

Order No  Time from Pickup to Arrival
0     Order_No_19248                         1350
1     Order_No_12736                         1103
2       Order_No_768                         1076
3     Order_No_15332                         1074
4     Order_No_21373                         1193
...              ...                          ...
7063   Order_No_3612                         1105
7064   Order_No_7657                         2826
7065   Order_No_1969                         1598
7066  Order_No_10591                         2456
7067   Order_No_1603                         1420

[7068 rows x 2 columns]

In [0]:
# Copying the result to a csv file
#final_df.to_csv('ArrivalTimes.csv', index=False)

# Ridge



In [719]:
# Importing the model class and training\fitting the model
from sklearn.linear_model import Ridge
ridge = Ridge()
ridge.fit(X_trans,y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [720]:
# Intercept
b_0 = ridge.intercept_
b_0

1382.0434369145773

In [721]:
# Coefficients of each independent variable
coeff = pd.DataFrame(ridge.coef_, X.columns, columns=['Coefficients'])
coeff

Coefficients
Personal or Business                -44.990964
Placement - Weekday (Mo = 1)          4.480685
Arrival at Pickup - Day of Month     -1.142612
Distance (KM)                       101.510397
Pickup Lat                          585.168009

In [722]:
# Time predictions using (Ridge regression) of each order in a dataframe
y_test_trans_ridge_pred = list(ridge.predict(X_test_trans))
y_test_pred_ridge_list = [int(round(i)) for i in y_test_trans_ridge_pred]
y_test_pred_ridge_df = pd.DataFrame(y_test_pred_ridge_list, columns=['Time from Pickup to Arrival'])
final_ridge_df = pd.concat([test.iloc[:,][['Order No']], y_test_pred_ridge_df], axis=1)
final_ridge_df

Order No  Time from Pickup to Arrival
0     Order_No_19248                         1352
1     Order_No_12736                         1103
2       Order_No_768                         1076
3     Order_No_15332                         1074
4     Order_No_21373                         1193
...              ...                          ...
7063   Order_No_3612                         1105
7064   Order_No_7657                         2826
7065   Order_No_1969                         1598
7066  Order_No_10591                         2455
7067   Order_No_1603                         1419

[7068 rows x 2 columns]

In [0]:
# Intercept
b_0 = ridge.intercept_

In [0]:
# Copying the result to a csv file
#final_ridge_df.to_csv('ArrivalTimesR.csv', index=False)

# Lasso

In [725]:
# Importing the model class
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.1)
lasso.fit(X_trans,y)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [726]:
# Intercept
b_0 = lasso.intercept_
b_0

1280.379101596238

In [727]:
# Coefficients of each independent variable
coeff = pd.DataFrame(lasso.coef_, X.columns, columns=['Coefficients'])
coeff

Coefficients
Personal or Business                -44.186737
Placement - Weekday (Mo = 1)          4.448187
Arrival at Pickup - Day of Month     -1.143187
Distance (KM)                       101.453983
Pickup Lat                          505.840738

In [728]:
# Time predictions using (Lasso regression) of each order in a dataframe
y_test_trans_lasso_pred = list(lasso.predict(X_test_trans))
y_test_pred_lasso_list = [int(round(i)) for i in y_test_trans_lasso_pred]
y_test_pred_lasso_df = pd.DataFrame(y_test_pred_lasso_list, columns=['Time from Pickup to Arrival'])
final_lasso_df = pd.concat([test.iloc[:,][['Order No']], y_test_pred_lasso_df], axis=1)
final_lasso_df

Order No  Time from Pickup to Arrival
0     Order_No_19248                         1356
1     Order_No_12736                         1103
2       Order_No_768                         1077
3     Order_No_15332                         1076
4     Order_No_21373                         1193
...              ...                          ...
7063   Order_No_3612                         1103
7064   Order_No_7657                         2825
7065   Order_No_1969                         1600
7066  Order_No_10591                         2451
7067   Order_No_1603                         1417

[7068 rows x 2 columns]

In [0]:
# Copying the result to a csv file
#final_lasso_df.to_csv('ArrivalTimesL.csv', index=False)